export function GetNetworkSettings() {
  return {
    autoResize: true,
    width: '100%',
    height: '100%',
    locale: 'en',
    locales: undefined,
    clickToUse: false,
    configure: {
      enabled: true,
      filter: true,
      container: undefined,
      showButton: true,
    },
    edges: {
      arrows: {
        to: { enabled: true, type: 'arrow', scaleFactor: 1 },
        from: { enabled: false },
        middle: { enabled: false },
      },
      color: {
        color: '#848484',
        highlight: '#848484',
        hover: '#848484',
        inherit: false,
        opacity: 1.0,
      },
      smooth: {
        enabled: false,
        type: 'straightCross',
        roundness: 0,
      },
      width: 1,
      selectionWidth: 1,
      hoverWidth: 1.5,
      shadow: false,
      font: { size: 12, face: 'arial', color: '#ff0000' },
      scaling: {
        label: true,
      },
    },
    nodes: {
      borderWidth: 1,
      borderWidthSelected: 2,
      shape: 'dot',
      image: undefined,
      brokenImage: undefined,
      color: {
        border: '#3366CC',
        background: '#99CCFF',
        highlight: { border: '#2B50AA', background: '#AAD4FF' },
        hover: { border: '#2B50AA', background: '#D2E5FF' },
      },
      font: {
        face: 'arial',
        color: '#343434',
        size: 14,
        background: 'none',
        strokeWidth: 0,
        strokeColor: '#ffffff',
      },
      icon: {
        face: 'FontAwesome',
        code: undefined,
        size: 50,
        color: '#2B7CE9',
      },
      shapeProperties: {
        useImageSize: false,
        useBorderWithImage: true,
        interpolation: false,
        coordinateOrigin: 'center',
      },
    },
    groups: {
      useDefaultGroups: true,
      myGroup: { color: { background: 'red' }, borderWidth: 3 },
    },
    layout: {
      randomSeed: undefined,
      improvedLayout: true,
      clusterThreshold: 150,
      hierarchical: {
        enabled: false,
        direction: 'UD',
        sortMethod: 'directed',
        levelSeparation: 150,
        nodeSpacing: 250,
        treeSpacing: 300,
        blockShifting: true,
        edgeMinimization: true,
        parentCentralization: true,
      },
    },
    interaction: {
      dragNodes: true,
      dragView: true,
      hideEdgesOnDrag: false,
      hideEdgesOnZoom: false,
      hideNodesOnDrag: false,
      hover: true,
      hoverConnectedEdges: true,
      keyboard: {
        enabled: false,
        speed: { x: 10, y: 10, zoom: 0.02 },
        bindToWindow: true,
      },
      multiselect: false,
      navigationButtons: true,
      selectable: true,
      selectConnectedEdges: true,
      tooltipDelay: 300,
      zoomSpeed: 1,
      zoomView: true,
    },
    manipulation: {
      enabled: false,
      initiallyActive: false,
      addNode: true,
      addEdge: true,
      editNode: undefined,
      editEdge: true,
      deleteNode: true,
      deleteEdge: true,
      controlNodeStyle: {},
    },
    physics: {
      enabled: true,
      solver: 'hierarchicalRepulsion',
      hierarchicalRepulsion: {
        centralGravity: 0.0,
        springLength: 100,
        springConstant: 0.01,
        nodeDistance: 200,
      },
      stabilization: {
        enabled: true,
        iterations: 200,
        updateInterval: 25,
        fit: true,
      },
      minVelocity: 0.75,
    },
  }
}
