import { DUMMY_ARN } from '../../constants';
import { AppContext } from '../../types';

export default {
  stackName: 'fastapi-task-stack',
  rollBack: 'true',
  appName: 'fastapi-task-appName',
  appType: 'fastapi-task',
  baseImagesAccountId: '767398142180',
  useSpot: 'true',
  ecsCircuitBreakerRollback: 'true',
  ecsHealthCheckGracePeriod: '0',
  containerPort: '8080',
  minContainers: '1',
  maxContainers: '1',
  reuseALB: 'true',
  ec2ALBListenerRulePrio: '1',
  targetGroupHealthCheckPath: '/health',
  targetGroupHealthCheckInterval: '30',
  targetGroupHealthCheckTimeout: '5',
  containerHealthCheckCmd: 'curl -f http://localhost:8080/health || exit 1',
  containerHealthCheckInterval: '30',
  containerHealthCheckTimeout: '5',
  containerHealthCheckRetries: '3',
  containerHealthCheckStartPeriod: '0',
  loadBalancerPort: '443',
  asgTargetValue: '50',
  useHANA: 'false',
  useBAR: 'true',
  useCDB: 'false',
  useAMB: 'false',
  expose2APIM: 'false',
  apimHost: 'api.alliander.com',
  cpu: '8192',
  memory: '61440',
  environment: 'prd',
  otap: 'P',
  environmentVariables: 'env1;env2;env3',
  useEFS: 'true',
  version: '0.1.83',
  jobSchedule: 'cron(0 7 ? * * *)',
  jobNotificationTopic: '',
  mainEntrypoint: 'run_application -m default',
  taskEntrypoint: 'run_application -m job -j default',
  verboseOutput: 'false',
  rdsSecurityGroupId: 'test-rds-security-group-id',
  repo: 'Alliander/Autobahn',
  branch: 'branch',
  commitSha: '1234',
  taskRoleArn: DUMMY_ARN,
  stsClientId: 'test-client-id',
  s3ApplicationDataBucketArn: DUMMY_ARN,
} satisfies AppContext;
