import { AppContext } from '../../types';
import { DUMMY_ARN } from '../../constants';

export default {
  stackName: 'autobahn-fahrgestell-test-python-streamlit',
  rollBack: 'true',
  appName: 'autobahn-fahrgestell-test-python-streamlit',
  appType: 'streamlit',
  baseImagesAccountId: '767398142180',
  useSpot: 'true',
  ecsCircuitBreakerRollback: 'true',
  ecsHealthCheckGracePeriod: '0',
  containerPort: '8080',
  minContainers: '1',
  maxContainers: '1',
  reuseALB: 'true',
  ec2ALBListenerRulePrio: '1',
  targetGroupHealthCheckPath: 'Auto',
  targetGroupHealthCheckInterval: '30',
  targetGroupHealthCheckTimeout: '5',
  containerHealthCheckCmd: 'Auto',
  containerHealthCheckInterval: '30',
  containerHealthCheckTimeout: '5',
  containerHealthCheckRetries: '3',
  containerHealthCheckStartPeriod: '0',
  loadBalancerPort: '443',
  asgTargetValue: '50',
  useHANA: 'false',
  useBAR: 'false',
  useCDB: 'false',
  useAMB: 'false',
  expose2APIM: 'false',
  apimHost: 'tst-api.alliander.com',
  cpu: '256',
  memory: '512',
  environment: 'tst',
  otap: 'T',
  environmentVariables: 'env1;env2;env3',
  useEFS: 'true',
  version: '0.1.3',
  jobSchedule: '',
  jobNotificationTopic: '',
  mainEntrypoint: 'run_application -m default',
  taskEntrypoint: 'run_application -m job -j default',
  verboseOutput: 'true',
  rdsSecurityGroupId: 'test-rds-security-group-id',
  repo: 'Alliander/Autobahn',
  branch: 'branch',
  commitSha: '1234',
  taskRoleArn: DUMMY_ARN,
  stsClientId: 'test-client-id',
  s3ApplicationDataBucketArn: DUMMY_ARN,
} satisfies AppContext;
